### ISSUE TITLE
AH Data

### ISSUE THREAD

**Issue by christianwensel** [josdemmers/NewWorldCompanion#1]
Hey I have a crude ah dumpers in python and my own postgres instance with price and price history.  I plan to just fork this repo to be able to present the data from my server. Just wanted to check with you to see if you were interested in me PRing back into it or not as it will effect my strategy. currently my data goes into a discord bot where I and friends can check it. HMU on discord if you like. solarwhale 0516

**Comment by christianwensel** [comment]
update i'll see what it takes for me to get my server data to the market price sit so it can be added as another source

**Comment by josdemmers** [comment]
Hi let me know how it goes with the server data.
You can find the discord server at https://nwmarketprices.com/ if you want to talk to the developer.
He is also busy working on adding more servers.
Currently the following are supported:
Camelot
El Dorado
Barri
Dry Tree
Midgard (soon?)

If you have data for another server he could probably use your help.

Regarding NewWorldCompanion, I have plans to create a better interface to support multiple sources. For example: https://new-world.exchange/
But that depends on how they make the data available. Currently only by private token so can't use that on a public repo.

If your server has a public API that is available then I could work on some ideas to get such an interface working.

ps. Update for NewWorldCompanion coming in 1-2 days. Adds support for all servers from https://nwmarketprices.com. Server list is updated at application launch. Also added tracker for all the ingame cooldowns.
