### ISSUE TITLE
(no data) for prices recently

### ISSUE THREAD

**Issue by cardona150** [josdemmers/NewWorldCompanion#11]
Starting a couple days ago I can't get pricing data "in-game":
![image](https://user-images.githubusercontent.com/575891/202302999-45d935bf-417e-4aa0-98d6-506b58494d19.png)
This is accompanied by "2022-11-16 13:55:22.9066|ERROR|NewWorldCompanion.Services.HttpClientHandler|MoveNext" in the logs. There is updated data for Olympus in nwmarketprices, not sure what the disconnect is here. Adding the uri of the "failed" call to the log could help me debug more here.

**Comment by josdemmers** [comment]
Thanks for the report. There is currently a problem with the nwmarketprices API.
The developer of nwmarketprices is already working on the problem.

Afterwards I'll have to make some changes as well for it to work correctly with the new API call.

**Comment by cardona150** [comment]
Ah, I just found this myself:
![image](https://user-images.githubusercontent.com/575891/202307846-668f9a06-6f87-49cd-9f11-ce5ff48db153.png)
LMK if I can help.

**Comment by josdemmers** [comment]
Will let you know, thanks for the offer.
Currently there is nothing we can do, we will just have to wait for the new nwmarketprices API call.

**Comment by josdemmers** [comment]
New API is ready. 
- recent_lowest_price is still working.
- timestamp is broken, only requires a small format change.
- avg price data is broken completely, requires some more work.

Current api example:
https://nwmarketprices.com/0/11/?cn_id=rawhidet1

Old api as reference
[oldapi.txt](https://github.com/josdemmers/NewWorldCompanion/files/10033842/oldapi.txt)

//edit
New API is still broken for servers that have not been updated recently.
Those will return a "Server Error (500)"

**Comment by josdemmers** [comment]
Fixed with the v1.0.9.0 update.
