### ISSUE TITLE
Winter Convergence GS600 patterns not showing prices

### ISSUE THREAD

**Issue by cardona150** [josdemmers/NewWorldCompanion#13]
Winter Convergence GS600 patterns not showing prices. Presumably because nwmarketprices doesn't include the (GS600) suffix variants in their DB.

**Comment by josdemmers** [comment]
Thanks for the report, I'll mention it in the Discord.
Not just the GS600 but normal patterns as well. Probably everything from Winter Convergence 2022?

Both "Pattern: Icebarrel" and "Pattern: Icebarrel (GS600)" return a 404 error.

Let me know if there are some that do work or that you only have a problem with a few of them.
In the log file you should be able to see the exact name it's trying to look for:
```
2022-12-10 22:40:56.2788|ERROR|NewWorldCompanion.Services.HttpClientHandler|GetRequest(https://nwmarketprices.com/0/24?cn_id=artifact_wcweaponblunderbuss)
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
```

**Comment by josdemmers** [comment]
All the "Winter Convergence 2022" items are now added on nwmarketprices.
So as soon as someone does a new scan for your server you should see the price info.

The developer of nwmarketprices mentioned there are still some issues with the GS600 patterns and will not always show up. He is going to fix that.

Are you on the nwmarketprices discord as well? He will probably post a message there when it's fixed.

**Comment by cardona150** [comment]
Ran a scan (Olympus server) and then went to the winter shop and mousedover every item, here are the logs:
[logging.log](https://github.com/josdemmers/NewWorldCompanion/files/10222232/logging.log)

Admittedly, something seems wrong with my scan, since it only has a few hundred items. In any case, "Pattern: Oak Regent Boots (GS600)" does have a price on nwmp (https://nwmarketprices.com/37735/33) but "https://nwmarketprices.com/0/1?cn_id=artifact_wcarmorheavyfeet600" returns 404.

Is this the fix we are waiting for?

**Comment by josdemmers** [comment]
No it should be working then. If you see the price at nwmarketprices it should be working with the overlay.
I think the fix we are waiting for is that the OCR sometimes doesn't understand the GS600 suffix. But in your scan it worked fine.

Thank you for the log file. Looks like an easy fix for you.
Your server is still set at the default price server.
If I change
https://nwmarketprices.com/0/1/?cn_id=artifact_wcarmorheavyfeet600
into
https://nwmarketprices.com/0/33/?cn_id=artifact_wcarmorheavyfeet600
it shows the correct price.

You can change the server by going to Config --> Overlay --> Select server.

**Comment by cardona150** [comment]
I noticed that. I was using an older version that wasn't aware of the items, and when I upgraded, it reset my server selection (along with my resolution). It seems to be working now. Is there a donations link for this project?

**Comment by josdemmers** [comment]
Thanks for the offer! Donations are not possible at the moment. Maybe I'll look into that later.
NewWorldCompanion started as a small project for my own, but only recently got more popular with the big New World update.

Regarding your configuration and to make your life easier. When updating you can copy the new version over the old version. That way it keeps all your configurations like server and resolution intact.

Probably a good idea to automate the update progress. I'll see if I can work on that later this month.

**Comment by josdemmers** [comment]
I did look around for donation options. Patreon is popular but only offers monthly subscriptions. Ko-fi seems a better choice as it offers one-time donations.
Ko-fi is now added on the GitHub project page and as a widget:
[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/H2H1H5GCR)
