### ISSUE TITLE
2023-01-11 Patch

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#14]
5.1GB patch today - if you wanted to scan through for any new recipe data and such :)

**Comment by josdemmers** [comment]
Thanks for letting me know, will make a new version this weekend with the updated game data.

**Comment by Marthisdil** [comment]
> 

Thanks!

**Comment by josdemmers** [comment]
Updated game data and small fix for the automatic updater.
Previous updater was bugged, you will probably have to update Updater.GitHub.exe by hand.
