### ISSUE TITLE
[feature request] Toggle to show missing/owned/both

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#15]
Would be nice if on the display there were toggles to show owned recipes, missing recipes, or both (all) recipes.  Lot faster that having to scroll down the long lists (esp furnishing) to see what you're missing.

Thanks for all the hard work!

**Comment by josdemmers** [comment]
That one is maybe a bit hidden. You can use right-mouse click to open the context menu and use that filter.
![image](https://user-images.githubusercontent.com/8627157/212134614-1342f675-4157-4950-9134-f1b4e7061192.png)

**Comment by Marthisdil** [comment]
Ah!  I never remotely thought to right click because it didn't seem obvious there.  Thanks!
