### ISSUE TITLE
DPS Counter?

### ISSUE THREAD

**Issue by James-Wilkinson-git** [josdemmers/NewWorldCompanion#16]
Unrelated but if you've the skills to make ocr app, wondering how we could make a DPS meter?

**Comment by josdemmers** [comment]
Unfortunately there is currently not a safe way to do this.

There are two (very small) possibilities for the future thought.

1. When New World / AGS decides to write combat logs to disk. This was already asked by the community back in 2021. So I don't think we will ever see this happen.
2. Easy Anti-Cheat prevents you from reading New World memory and getting useful game data. Overwolf is however whitelisted by Easy Anti-Cheat and can read the player position. This is used for New World minimaps to show the actual player position. e.g. https://www.overwolf.com/app/Leon_Machens-Aeternum_Map.
Overwolf has communicated with New World / AGS to get more data besides player position but currently New World / AGS has no plans for this.
