### ISSUE TITLE
No longer working in NW

### ISSUE THREAD

**Issue by ERRORxEXTINCTION** [josdemmers/NewWorldCompanion#19]
After performing a fresh install of Windows the companion app no longer works within NW.  Config is set to the way it was before but I no longer see the overlay example under Screen Process or Screen OCR. Anything I'm missing? Thanks!

**Comment by josdemmers** [comment]
You mentioned a fresh install, so it's probably related to a resolution config somewhere.
Could you try the following?
- First make sure both Windows and New World are using the same resolution.
- Then go to the config for Screen processing in the NewWorldCompanion App and select the resolution you are currently using.

**Comment by ERRORxEXTINCTION** [comment]
I realized I installed Win 11 (N) which didn't come with any media support. I wasn't able to play spotify without the "Media Pack" and installed it and for some reason all is well again. Not sure how that would have affected it? I appreciate you taking time to respond! Love the work you put in and appreciate your work.

**Comment by josdemmers** [comment]
Thank you, glad you like it!

Not familiar with that "Media Pack" but good to know you solved it. Might be some dependencies that are missing when doing a fresh install of Win 11 (N).
Are there any error messages about this in the log file? Could be useful when someone else has the same issue in the future.
