### ISSUE TITLE
NW Client Update

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#21]
Update recently - mind updating the game data for the app?

Thanks!

**Comment by josdemmers** [comment]
Probably the one from early March? Or maybe that special 1st April edition.
But no significant changes, so I skipped that one.

Only change in the game data was the added `ObtainableReleaseVersion` property for items (that is not being used).

**Comment by josdemmers** [comment]
Yesterdays update had multiple changes. Will release a new version later today.
