### ISSUE TITLE
In price game overlay not working on 4k

### ISSUE THREAD

**Issue by armourg** [josdemmers/NewWorldCompanion#23]
Can't seem to get prices working at all on 4k. I tried 1440p to see if that would work and it did but I can't figure out 4k at all. Windows resolution, in game resolution and NWC resolution all set to 4k.

**Comment by josdemmers** [comment]
Did you press the "load config" button to load the 4k configuration?
![image](https://github.com/josdemmers/NewWorldCompanion/assets/8627157/499fb610-3b15-4257-b3c4-e427b38abda5)

**Comment by armourg** [comment]
I did yeah, I seem to be able to get it working on any other resolution just not 4k.

**Comment by josdemmers** [comment]
![image](https://github.com/josdemmers/NewWorldCompanion/assets/8627157/b58f4f0d-1427-4ff7-9e78-5e973adc6642)

After loading the 4k config you can try to manually change the area threshold a bit. This setting is used to detect the square of the item icons.
The left slider is for the minimum value, the right slider for the maximum value.

Try to decrease the left slider a bit, and to increase the right slider.

**Comment by armourg** [comment]
Ah perfect got it thanks, 16,600 left and 31,200 right seems like the sweet spot for me.
