### ISSUE TITLE
Data Update - Current release

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#24]
hey bud!  Wanted to check to see if the data needed to be updated, etc, for current release/any updates to NWMP

Thanks for the tool!

**Comment by josdemmers** [comment]
You're welcome! Not sure about any new items, last update was from 3.0, so has been a while.
I'll will check later this week if there are any changes.

**Comment by josdemmers** [comment]
Looks like I have to change my parser first.
First I could use a single CraftingRecipes.json containing all the data but looks like that is now split in multiple files for each category.
Can probably look into this in the weekend.

![image](https://github.com/josdemmers/NewWorldCompanion/assets/8627157/e204e0c2-5dc2-4015-a81b-a72e4e4a7c1e)

**Comment by Marthisdil** [comment]
Thanks for the update!  Appreciate ya!

**Comment by josdemmers** [comment]
v1.12.10 is ready. Fixed an issue with nwmarketprices.com and updated all the item data.
