### ISSUE TITLE
loading prices all at ones

### ISSUE THREAD

**Issue by kampari89** [josdemmers/NewWorldCompanion#5]
loading the prices often takes forever or they don't load at all. since the prices are queried individually each time. wouldn't it make more sense to query all prices via the export when starting the program?

**Comment by josdemmers** [comment]
Thanks for letting me know, I posted about the delay on the nwmarketprices.com discord.
Unfortunately the export does not contain all the information needed for the tooltip.

Requesting price data of a single item also contains price history.
Requesting data should take less than a second normally when the website is working correct. Currently it takes 10-20 seconds, so definitely something wrong there.

When you experience the issue again you could post it on their discord so they can fix it.

To test the delay on the website you could use the crafting tab, select an item, and wait until you see the price show up. That might be easier than testing it with the tooltip.

![image](https://user-images.githubusercontent.com/8627157/176184869-ec236de0-2c0d-4681-91c2-b59a3073bbd0.png)

**Comment by josdemmers** [comment]
No plans for using the export to load everything at once because of missing data
