### ISSUE TITLE
Brimstone patch - apparently new schematics

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#7]
can you do a quick parse of nwdb to add any new recipes/sheet music?  Thanks!

**Comment by josdemmers** [comment]
Extracted the new game data for the Brimstone update. Unfortunately I'm getting exceptions when importing the data. Looks like something changed in the data structure.
Takes a bit longer now, maybe tonight, otherwise I'll fix it in the weekend.

**Comment by josdemmers** [comment]
False alarm, exception was caused by a duplicate in the exported data. Removed the duplicate and everything works fine now.

**Comment by josdemmers** [comment]
Released v1.0.7.2

**Comment by Marthisdil** [comment]
Thanks so much!  Drop me a line on Discord sometime :)
