### ISSUE TITLE
v1.0.8.0 - copy/paste issue

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#8]
the game won't accept a paste when clicking the copy icon for a tradeskill entry.

pasting into notepad works.

copying and pasting FROM notepad works.

my guess is some weird hidden character/formatting preventing the game client from accepting the info on the clipboard put there by the companion app

**Comment by josdemmers** [comment]
Correct, New World blocks all special chars for input fields.
Looks like something new was added or a recent change by me broke it.

Does it happen for all trade skill entries or only the Music sheets?
Music sheets have multiple "new line" characters, although I was sure I removed them all in a previous update.

//edit

The "/" in `Before the Storm Azoth Flute Sheet Music Page 1/2` is probably causing issues as well.
Will look into this tomorrow.

**Comment by Marthisdil** [comment]
Just tried with Schematic: Chraftsman's Passion (new WS recipe).

Clicked the copy icon in NWC 1.0.8.0

Pasted into the search field, and just Craftsman was pated in

Clicked copy icon again, pasted into Notepad, only Craftsman was pasted into notepad.

**Comment by josdemmers** [comment]
Yes for those items I did that on purpose:
![image](https://user-images.githubusercontent.com/8627157/197877530-fb6b25a7-0c8e-438e-9987-3c58330ef274.png)

Special chars like ' and : are ignored and skipped. Otherwise the copy/paste is blocked completely by New World.

But do you have an example of the issue you mentioned in your first message, where the paste was blocked completely?
Because that would mean there is another special char besides ' and : that is blocked. Or was that the / for the Sheet Music I mentioned earlier?

**Comment by josdemmers** [comment]
And how would you like the Music Sheets to be handled.
**Original string from New World**
Blacksmith Arm \n Guitar Sheet Music \n Page 1/3
**Without new lines**
Blacksmith Arm Guitar Sheet Music Page 1/3

Trading Post search:
![image](https://user-images.githubusercontent.com/8627157/197878907-a07e1c61-14fa-4ca6-8aa7-c1354c27b51b.png)

Search returns only results if you use the text until the first new line (\n).
That would mean "Blacksmith Arm Guitar Sheet Music Page 1/3"
Becomes "Blacksmith Arm"

If you copy/paste more from the item name it wont return any results.

**Comment by Marthisdil** [comment]
Yup!

Canarios Guitar Sheet Music Page 1/1

edit: also happens with Fellows of Windsward Drums Sheet Music Page 1/1
Fellows of Windsward Guitar Sheet Music Page 1/1
Fellows of Windsward Mandolin Sheet Music Page 1/1
Fellows of Windsward Second Guitar Sheet Music Page 1/1
Fellows of Windsward Upright Bass Sheet Music Page 1/1
My Home Drums Sheet Music Page 1/1
My Home Guitar Sheet Music Page 1/1
My Home Second Guitar Sheet Music Page 1/1
Sounds of Bells Guitar Sheet Music Page 2/3

spot checked other songs (Blacksmith Arm series, etc), and it happens with them as well.



Clicking copy icon copies to clipboard (used it to paste here) - trying to paste into the search box in game doesn't paste anything.

**Comment by josdemmers** [comment]
In v1.0.8.1 music sheet names will only contain the first part after a copy/paste so that you can directly use it in the trading post.
Example:
`Fellows of Windsward Drums Sheet Music Page 1/1` becomes `Fellows of Windsward`
