### ISSUE TITLE
[Data Update] Patch 1.7.1

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#9]
Thanks for the recent bugfix!  AGS has updated some recipes to no longer be BOP.  Wanted to post here in case that means addl data needs to be pulled in!

- Fixed an issue that made Nightveil patterns Bind on Pickup instead of Bind on Equip.

https://www.newworld.com/en-us/news/articles/new-world-update-1-7-1

**Comment by josdemmers** [comment]
You are fast! But thanks for notifying me.
Already extracted the new data from the game files. And added a default config for the 1600x900 resolution.
Will release the new version later today.

**Comment by josdemmers** [comment]
Thanks for the report, fixed with the v1.0.8.2 release.
